name: editora_izyncor_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  quickalert: ^1.0.1
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.0.10 #Armazenamento de arquivos
  firebase_auth: ^4.2.5 #Autenticação de usuário
  cached_network_image: ^3.1.0
  firebase_core: ^2.15.1 #Recursos básicos
  image: ^3.0.3
  image_cropper: ^1.4.1
  path_provider: ^2.0.5
  cloud_firestore: ^4.7.1
  emoji_keyboard_flutter: ^1.3.1
  flutter_emoji: ^2.4.0
  readmore: ^2.2.0
  skeletons: ^0.0.3
  like_button: ^2.0.5
  flutter_colorpicker: ^1.0.3
  http: ^0.13.4
  qr_flutter: ^4.0.0
  mercadopago_sdk: ^1.3.0
  webview_flutter: ^3.0.4
  loading_animation_widget: ^1.2.0+4
  firebase_messaging: ^14.6.8
  flutter_animate: ^4.2.0+1
  dotted_border: ^2.0.0+3
  google_nav_bar: ^5.0.6
  flutter_sound_lite: ^8.5.0
  permission_handler: ^11.0.0
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash2.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/icone2.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_backgroud: "#ffffff"
  adaptive_icon_foreground: "assets/icone.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background_cadastro.png
    - assets/background_options.jpg
    - assets/logo_apple.png
    - assets/logo_facebook.png
    - assets/logo_google.png
    - assets/logo_izyncor01.png
    - assets/logo_izyncor02.png
    - assets/topo_login.png
    - assets/vaso_inicial.png
    - assets/inicio_circulo.png
    - assets/inicio_circulo2.png
    - assets/inicio_circulo3.png
    - assets/inicio_garoto.png
    - assets/inicio_garota.png
    - assets/inicio_homen.png
    - assets/inicio_texto1.png
    - assets/inicio_texto2.png
    - assets/inicio_texto3.png
    - assets/izyncor.png
    - assets/pesquisar2.png
    - assets/capa_caligem.jpg
    - assets/capa_ecos.png
    - assets/modeloport.jpg
    - assets/PARALLAX.jpg
    - assets/ecos-banner-2.png
    - assets/ecos-banner-3.png
    - assets/ecos2-alta-usar.png
    - assets/fundo_caligem.jpg
    - assets/carrinho.png
    - assets/logoizyncor.png
    - assets/logobanner.png
    - assets/splash.png
    - assets/oculosicone.png
    - assets/relogioicone.png
    - assets/boleto.jpg
    - assets/moldura.png
    - assets/verificado.png
    - assets/971.jpg
    - assets/wll.png
    - assets/izyncorskob.jpeg
    - assets/fundoizyncor.jpg
    - assets/trecho.jpeg
    - assets/logo_casa.png
    - assets/logo_chat.png
    - assets/logo_loja.png
    - assets/logo_loja2.png
    - assets/logo_perfil.png
    - assets/tela_01_1.jpg
    - assets/tela_02_1.jpg
    - assets/tela_03_1.jpg
    - assets/foto_leandro.png
    - assets/foto_thais.png
    - assets/fundo_chat.png
    - assets/chat_back.jpg
    - assets/home_01.png
    - assets/home_02.png
    - assets/comment_01.png
    - assets/comment_02.png
    - assets/comment_03.png
    - assets/comment_04.png
    - assets/shop_01.png
    - assets/shop_02.png
    - assets/add_01.png
    - assets/add_02.png
    - assets/user_01.png
    - assets/user_02.png
    - assets/curtir_01.png
    - assets/curtir_02.png
    - assets/curtir_03.png
    - assets/send.png
    - assets/send3.png
    - assets/pesquisa.png
    - assets/salvar_01.png
    - assets/salvar_02.png
    - assets/salvar_03.png
    - assets/salvar_04.png
    - assets/ds_01.png
    - assets/ds_02.png
    - assets/galeria.png
    - assets/galeria_02.png
    - assets/textos_02.png
    - assets/coracao_03.png
    - assets/comentar_post.png
    - assets/coracao_02.png
    - assets/coracao_01.png
    - assets/coracao_04.png
    - assets/disquete.png
    - assets/disquete_08.png
    - assets/options_02.png
    - assets/options.png
    - assets/compartilhar.png
    - assets/compartilhar_branco.png
    - assets/disquete_08_branco.png
    - assets/disquete_06_branco.png
    - assets/comentar_branco.png
    - assets/coracao_01_branco.png
    - assets/denunciar_01.png
    - assets/copiar.png
    - assets/lixeira.png
    - assets/settings.png
    - assets/logo.png
    - assets/logo2.png
    - assets/logo3.png
    - assets/camera2.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: UltraCondensedSansSerif
      fonts:
        - asset: assets/fonts/UltraCondensedSansSerif.ttf
